import pandas as pd
from pathlib import Path
from openpyxl.styles import PatternFill, Font, Alignment
from openpyxl.utils import get_column_letter

DATA_DIR = Path("data")
OUTPUT_DIR = Path("output")

def read_csv_safe(path):
    try:
        if path.exists() and path.stat().st_size > 0:
            return pd.read_csv(path)
    except pd.errors.EmptyDataError:
        pass
    return pd.DataFrame()

def autosize(ws):
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            value = "" if cell.value is None else str(cell.value)
            max_len = max(max_len, len(value))
        ws.column_dimensions[col_letter].width = min(max_len + 2, 36)

def style_sheet(ws):
    for cell in ws[1]:
        cell.fill = PatternFill("solid", fgColor="1F4E78")
        cell.font = Font(color="FFFFFF", bold=True)
        cell.alignment = Alignment(horizontal="center", vertical="center")

    for row in ws.iter_rows():
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)

    autosize(ws)

def highlight_actions(ws, action_header):
    headers = [cell.value for cell in ws[1]]
    if action_header not in headers:
        return

    action_col = headers.index(action_header) + 1

    for row in ws.iter_rows(min_row=2):
        action = row[action_col - 1].value

        if action == "SELL":
            fill = PatternFill("solid", fgColor="F4CCCC")
        elif action == "TRIM":
            fill = PatternFill("solid", fgColor="FCE4D6")
        elif action == "BUY":
            fill = PatternFill("solid", fgColor="C6EFCE")
        elif action == "BUY SMALL":
            fill = PatternFill("solid", fgColor="D9EAF7")
        elif action == "HOLD":
            fill = PatternFill("solid", fgColor="E2F0D9")
        elif action == "WATCH":
            fill = PatternFill("solid", fgColor="FFF2CC")
        else:
            fill = None

        if fill:
            for cell in row:
                cell.fill = fill

def build_excel_workbook():
    OUTPUT_DIR.mkdir(exist_ok=True)

    files = {
        "Dashboard": DATA_DIR / "dashboard.csv",
        "Holdings": DATA_DIR / "holdings_view.csv",
        "Trades": DATA_DIR / "trades.csv",
        "Performance Summary": DATA_DIR / "performance_summary.csv",
        "Weekly Review": DATA_DIR / "weekly_review.csv",
        "Signals Full": DATA_DIR / "signals.csv",
        "Premarket Full": DATA_DIR / "premarket_signals.csv",
        "Market Data": DATA_DIR / "market_data.csv",
    }

    excel_file = OUTPUT_DIR / "trading_summary.xlsx"

    with pd.ExcelWriter(excel_file, engine="openpyxl") as writer:
        for sheet, path in files.items():
            df = read_csv_safe(path)

            if df.empty:
                df = pd.DataFrame([{"status": "No data available yet"}])

            df.to_excel(writer, sheet_name=sheet, index=False)

        instructions = pd.DataFrame([
            {"Step": 1, "Action": "Open Dashboard first. It is the clean action view generated by GitHub."},
            {"Step": 2, "Action": "Review SELL / TRIM rows before any buys."},
            {"Step": 3, "Action": "Check Holdings and Performance Summary before trading."},
            {"Step": 4, "Action": "Use BUY / BUY SMALL as candidates, not automatic trades."},
            {"Step": 5, "Action": "For full sells in trades.csv, use shares=ALL."},
            {"Step": 6, "Action": "Run GitHub workflow, then refresh Excel."},
        ])
        instructions.to_excel(writer, sheet_name="How To Use", index=False)

        wb = writer.book

        for ws in wb.worksheets:
            style_sheet(ws)

            if ws.title == "Dashboard":
                highlight_actions(ws, "action_required")

            if ws.title == "Signals Full":
                highlight_actions(ws, "action")

            if ws.title == "Premarket Full":
                highlight_actions(ws, "premarket_action")

    print(f"Excel workbook created: {excel_file}")
    return excel_file

if __name__ == "__main__":
    build_excel_workbook()
